# Generated by Django 6.0.7 on 2026-07-16 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagencyapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('region', models.CharField(help_text='e.g. Zanzibar, Arusha, Serengeti', max_length=100)),
                ('category', models.CharField(choices=[('national_park', 'National Park'), ('mountain', 'Mountain'), ('beach', 'Beach / Island'), ('cultural', 'Cultural / Historical'), ('city', 'City / Urban')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200)),
                ('entry_fee', models.CharField(blank=True, max_length=200)),
                ('activities', models.TextField(blank=True, help_text='Comma separated list of activities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('zanzibar', 'Zanzibar Tours'), ('tanzania', 'Tanzania Safaris'), ('international', 'International')], default='international', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='excludes',
            field=models.TextField(blank=True, help_text='Comma separated list of exclusions'),
        ),
        migrations.AddField(
            model_name='tour',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes',
            field=models.TextField(blank=True, help_text='Comma separated list of inclusions'),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='travelagencyapp.tour')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travelagencyapp.tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
