# Generated by Django 5.2.7 on 2026-07-17 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagencyapp', '0003_traveltip_visitortracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('zanzibar_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('tanzania_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Setting',
                'verbose_name_plural': 'Home Settings',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_time_mins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_maps_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TourGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='travelagencyapp.tour')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
