# Generated by Django 5.2.7 on 2026-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagencyapp', '0004_homesetting_booking_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='category',
            field=models.CharField(blank=True, choices=[('national_park', 'National Park'), ('mountain', 'Mountain'), ('beach', 'Beach / Island'), ('cultural', 'Cultural / Historical'), ('city', 'City / Urban')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='region',
            field=models.CharField(blank=True, default='', help_text='e.g. Zanzibar, Arusha, Serengeti', max_length=100),
        ),
    ]
