# Generated by Django 5.2.7 on 2026-07-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagencyapp', '0005_alter_attraction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
