# Generated by Django 5.2.7 on 2026-07-17 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagencyapp', '0007_tour_json_include_exclude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'tour')},
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author_title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='hidden',
        ),
    ]
