# Generated by Django 6.0.7 on 2026-07-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelagencyapp', '0009_contactmessage_is_read_contactmessage_phone_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
