from django.core.management.base import BaseCommand
from travelagencyapp.models import Tour, Attraction, Review, ItineraryItem

class Command(BaseCommand):
    help = 'Seed the database with Zanzibar and Tanzania travel data'

    def handle(self, *args, **kwargs):
        Tour.objects.all().delete()
        Attraction.objects.all().delete()
        Review.objects.all().delete()
        ItineraryItem.objects.all().delete()

        tours = [
            # === ZANZIBAR TOURS ===
            {
                'title': 'Zanzibar Beach Paradise',
                'short_description': 'Relax on pristine white beaches of Zanzibar with crystal clear turquoise waters',
                'description': 'Experience the ultimate beach getaway on the stunning island of Zanzibar. This tour takes you to the best beaches including Nungwi, Kendwa, and Paje. Enjoy swimming, snorkeling, sunset dhow cruises, and fresh seafood dining on the beach. Perfect for honeymooners and beach lovers looking for tropical paradise.',
                'price': 899.00,
                'duration': '5 Days / 4 Nights',
                'destination': 'Zanzibar, Tanzania',
                'category': 'zanzibar',
                'includes': 'Hotel accommodation, Breakfast daily, Airport transfers, Beach activities, Snorkeling gear, Sunset dhow cruise',
                'excludes': 'Flights, Lunch & dinner, Personal expenses, Travel insurance',
                'available': True,
                'featured': True,
            },
            {
                'title': 'Zanzibar Stone Town & Spice Tour',
                'short_description': 'Explore the historic Stone Town and visit aromatic spice farms',
                'description': 'Discover the rich history and culture of Zanzibar through its UNESCO World Heritage Site, Stone Town. Wander through narrow alleys, visit the House of Wonders, Old Fort, and the former slave market. Then embark on a spice tour to learn about Zanzibar famous spices like cloves, nutmeg, cinnamon, and vanilla. Taste exotic fruits and see how spices are grown and processed.',
                'price': 549.00,
                'duration': '3 Days / 2 Nights',
                'destination': 'Zanzibar, Tanzania',
                'category': 'zanzibar',
                'includes': 'Hotel accommodation, Guided Stone Town tour, Spice farm tour, Breakfast, Airport transfers',
                'excludes': 'Flights, Lunch & dinner, Personal expenses',
                'available': True,
                'featured': True,
            },
            {
                'title': 'Zanzibar Snorkeling & Diving Adventure',
                'short_description': 'Discover vibrant coral reefs and marine life around Zanzibar islands',
                'description': 'Dive into the crystal clear waters of Zanzibar and explore some of the best coral reefs in East Africa. Visit Mnemba Atoll, a protected marine reserve teeming with colorful fish, sea turtles, and dolphins. Snorkel at the famous Blue Lagoon and explore the sandbanks of the Indian Ocean. Professional diving instructors available for beginners.',
                'price': 699.00,
                'duration': '4 Days / 3 Nights',
                'destination': 'Zanzibar, Tanzania',
                'category': 'zanzibar',
                'includes': 'Beach resort accommodation, Daily breakfast, 2 snorkeling trips, 1 diving session, Equipment rental, Beach BBQ dinner',
                'excludes': 'Flights, Extra drinks, Personal expenses, Tips',
                'available': True,
                'featured': False,
            },
            {
                'title': 'Zanzibar Luxury Honeymoon Package',
                'short_description': 'Ultimate romantic getaway in Zanzibar luxury resorts',
                'description': 'Celebrate your love with the ultimate romantic escape in Zanzibar. Stay at 5-star beachfront resorts with private pools and butler service. Enjoy couples spa treatments, private candlelit dinners on the beach, sunset dhow cruises, and a romantic getaway to the exotic Prison Island to see giant tortoises. Includes private transfers and a honeymoon cake.',
                'price': 1899.00,
                'duration': '7 Days / 6 Nights',
                'destination': 'Zanzibar, Tanzania',
                'category': 'zanzibar',
                'includes': 'Luxury resort accommodation, All meals, Couples spa treatment, Private dhow cruise, Airport transfers, Honeymoon cake, Fruit basket',
                'excludes': 'Flights, Personal expenses, Extra spa treatments',
                'available': True,
                'featured': True,
            },
            {
                'title': 'Jozani Forest & Prison Island Tour',
                'short_description': 'Explore the only national park in Zanzibar and historic Prison Island',
                'description': 'Visit Jozani Chwaka Bay National Park, home to the rare Red Colobus monkeys found only in Zanzibar. Walk through the lush mangrove forests and learn about the unique ecosystem. Then take a boat to Prison Island (Changuu Island) to see the giant Aldabra tortoises, some over 100 years old. Snorkel in the pristine waters around the island.',
                'price': 449.00,
                'duration': '2 Days / 1 Night',
                'destination': 'Zanzibar, Tanzania',
                'category': 'zanzibar',
                'includes': 'Hotel accommodation, Park entrance fees, Guided forest walk, Boat transfer to Prison Island, Breakfast',
                'excludes': 'Flights, Lunch, Personal expenses',
                'available': True,
                'featured': False,
            },
            {
                'title': 'Zanzibar Cultural & Food Experience',
                'short_description': 'Taste your way through Zanzibar rich culinary heritage',
                'description': 'Immerse yourself in Zanzibari culture through its food. Take a guided food tour through the streets of Stone Town tasting Zanzibar pizza, urojo soup, fresh sugarcane juice, and traditional Swahili dishes. Visit the Forodhani Night Market, take a cooking class to learn how to make biryani and samosas, and visit local villages to experience authentic Zanzibari hospitality.',
                'price': 599.00,
                'duration': '4 Days / 3 Nights',
                'destination': 'Zanzibar, Tanzania',
                'category': 'zanzibar',
                'includes': 'Boutique hotel accommodation, Daily breakfast, 2 cooking classes, Food walking tour, Village visit, Market tour',
                'excludes': 'Flights, Extra meals, Personal expenses',
                'available': True,
                'featured': False,
            },
            # === TANZANIA SAFARIS ===
            {
                'title': 'Serengeti Safari Experience',
                'short_description': 'Witness the Great Migration and Big Five in Serengeti National Park',
                'description': 'Embark on the safari of a lifetime in the world-famous Serengeti National Park. Witness the Great Migration of wildebeest and zebras, spot the Big Five (lion, leopard, elephant, rhino, buffalo), and experience the vast African plains. Stay in luxury tented camps and enjoy game drives with experienced guides. This is the ultimate African safari adventure.',
                'price': 2499.00,
                'duration': '6 Days / 5 Nights',
                'destination': 'Serengeti, Tanzania',
                'category': 'tanzania',
                'includes': 'Full-board accommodation, Park entrance fees, Game drives, Professional guide, Airport transfers, Safari vehicle',
                'excludes': 'Flights, Drinks, Tips, Travel insurance, Visa fees',
                'available': True,
                'featured': True,
            },
            {
                'title': 'Kilimanjaro Trekking Adventure',
                'short_description': 'Conquer the Roof of Africa - Mount Kilimanjaro',
                'description': 'Challenge yourself to climb the highest peak in Africa, Mount Kilimanjaro (5,895m). Follow the scenic Machame Route through rainforest, alpine meadows, and lunar landscapes to the snowy summit at Uhuru Peak. Professional guides, porters, and all camping equipment provided. Witness breathtaking sunrise views from the top of Africa.',
                'price': 2999.00,
                'duration': '8 Days / 7 Nights',
                'destination': 'Mount Kilimanjaro, Tanzania',
                'category': 'tanzania',
                'includes': 'Park entrance fees, Professional guides, Porters, Camping equipment, All meals on mountain, Oxygen tank, Emergency evacuation',
                'excludes': 'Flights, Tips, Sleeping bag, Personal gear, Travel insurance',
                'available': True,
                'featured': True,
            },
            {
                'title': 'Ngorongoro Crater Tour',
                'short_description': 'Explore the stunning Ngorongoro Crater - Africa Garden of Eden',
                'description': 'Descend into the Ngorongoro Crater, a UNESCO World Heritage Site and one of the most beautiful natural wonders in Africa. This massive volcanic caldera is home to over 25,000 animals including the Big Five. Enjoy a full-day game drive on the crater floor, visit Lake Magadi to see flamingos, and learn about the Maasai people who live in the area.',
                'price': 1599.00,
                'duration': '3 Days / 2 Nights',
                'destination': 'Ngorongoro, Tanzania',
                'category': 'tanzania',
                'includes': 'Lodge accommodation, Full-board meals, Crater entrance fee, Game drive, Professional guide, 4x4 safari vehicle',
                'excludes': 'Flights, Drinks, Tips, Travel insurance',
                'available': True,
                'featured': True,
            },
            {
                'title': 'Tarangire & Manyara Safari',
                'short_description': 'Discover Tarangire elephants and Lake Manyara tree-climbing lions',
                'description': 'Visit two of Tanzania most beautiful parks. Tarangire National Park is famous for its massive elephant herds and ancient baobab trees. Lake Manyara National Park offers diverse wildlife including the famous tree-climbing lions, large flocks of flamingos, and lush groundwater forests. Perfect combination for wildlife photography enthusiasts.',
                'price': 1299.00,
                'duration': '4 Days / 3 Nights',
                'destination': 'Tarangire & Manyara, Tanzania',
                'category': 'tanzania',
                'includes': 'Lodge accommodation, All meals, Park entrance fees, Game drives, Professional guide, 4x4 vehicle',
                'excludes': 'Flights, Drinks, Tips, Travel insurance',
                'available': True,
                'featured': False,
            },
            {
                'title': 'Tanzania Northern Circuit Grand Safari',
                'short_description': 'Complete safari covering Serengeti, Ngorongoro, Manyara, and Tarangire',
                'description': 'The ultimate Tanzania safari covering all the major parks of the Northern Circuit. Start at Tarangire, continue to Lake Manyara, explore the Ngorongoro Crater, and spend multiple days in the Serengeti. Witness the Great Migration, spot the Big Five, visit Maasai villages, and experience the best that Tanzania has to offer in one comprehensive safari package.',
                'price': 3999.00,
                'duration': '10 Days / 9 Nights',
                'destination': 'Tanzania Northern Circuit',
                'category': 'tanzania',
                'includes': 'All accommodation (lodges & tented camps), All meals, Park entrance fees, Game drives, Professional English-speaking guide, Airport transfers, 4x4 safari vehicle, Maasai village visit',
                'excludes': 'Flights, Visa, Travel insurance, Tips, Personal expenses',
                'available': True,
                'featured': True,
            },
            {
                'title': 'Selous & Ruaha Wilderness Safari',
                'short_description': 'Off-the-beaten-path safari in Tanzania largest reserves',
                'description': 'Escape the crowds and explore the remote wilderness of Selous Game Reserve and Ruaha National Park. Enjoy boat safaris on the Rufiji River, walking safaris with expert rangers, and game drives in untouched landscapes. These parks offer a more exclusive safari experience with fewer tourists and incredible wildlife sightings including wild dogs, elephants, and lions.',
                'price': 2799.00,
                'duration': '7 Days / 6 Nights',
                'destination': 'Selous & Ruaha, Tanzania',
                'category': 'tanzania',
                'includes': 'Camp/lodge accommodation, All meals, Park fees, Game drives, Boat safari, Walking safari, Professional guide',
                'excludes': 'Flights, Drinks, Tips, Travel insurance',
                'available': True,
                'featured': False,
            },
            {
                'title': 'Zanzibar & Safari Combo',
                'short_description': 'Best of both worlds - Serengeti safari and Zanzibar beach relaxation',
                'description': 'Experience the perfect combination of an African safari and tropical beach vacation. Start with a 4-day Serengeti safari witnessing the Great Migration and Big Five, then fly to Zanzibar for 4 days of pure relaxation on pristine beaches. This combo tour offers the ultimate Tanzania experience - adventure and paradise in one trip.',
                'price': 3499.00,
                'duration': '10 Days / 9 Nights',
                'destination': 'Serengeti & Zanzibar, Tanzania',
                'category': 'tanzania',
                'includes': 'All accommodation, Park entrance fees, Game drives, Serengeti-Zanzibar flight, Beach resort, Meals as per itinerary',
                'excludes': 'International flights, Visa, Travel insurance, Tips, Personal expenses',
                'available': True,
                'featured': True,
            },
            {
                'title': 'Lake Victoria & Rubondo Island Safari',
                'short_description': 'Explore the largest lake in Africa and pristine Rubondo Island',
                'description': 'Discover the hidden gem of Rubondo Island National Park on Lake Victoria. This unique safari combines boat excursions on Africas largest lake, chimpanzee tracking in pristine forests, and game viewing in an untouched ecosystem. Enjoy fishing, bird watching with over 400 species, and exploring the tranquil island paradise.',
                'price': 1899.00,
                'duration': '5 Days / 4 Nights',
                'destination': 'Lake Victoria, Tanzania',
                'category': 'tanzania',
                'includes': 'Lodge accommodation, All meals, Park fees, Boat excursions, Chimpanzee tracking, Fishing equipment, Professional guide',
                'excludes': 'Flights, Drinks, Tips, Travel insurance',
                'available': True,
                'featured': False,
            },
        ]

        for tour_data in tours:
            tour = Tour.objects.create(**tour_data)
            self.stdout.write(f'  Created tour: {tour.title}')

        attractions = [
            # === TANZANIA ATTRACTIONS ===
            {
                'name': 'Serengeti National Park',
                'description': 'One of the most famous wildlife parks in the world, the Serengeti is home to the Great Migration of wildebeest and zebras, the Big Five, and vast savannah plains. It covers 14,750 sq km and offers unparalleled safari experiences.',
                'location': 'Northern Tanzania',
                'region': 'Serengeti',
                'category': 'national_park',
                'best_time_to_visit': 'June to October (dry season)',
                'entry_fee': '$70 per person per day (international)',
                'activities': 'Game drives, Hot air balloon safaris, Walking safaris, Photography, Bird watching',
            },
            {
                'name': 'Ngorongoro Crater',
                'description': 'A UNESCO World Heritage Site, the Ngorongoro Crater is the worlds largest inactive volcanic caldera. It is often called "Africa Garden of Eden" due to its dense wildlife population including the Big Five, flamingos, and over 500 bird species.',
                'location': 'Arusha Region, Northern Tanzania',
                'region': 'Ngorongoro',
                'category': 'national_park',
                'best_time_to_visit': 'June to September and December to March',
                'entry_fee': '$70 per person per day',
                'activities': 'Game drives, Crater rim walks, Maasai village visits, Photography, Bird watching',
            },
            {
                'name': 'Mount Kilimanjaro',
                'description': 'The highest peak in Africa at 5,895 meters, Mount Kilimanjaro is one of the Seven Summits. This dormant volcano offers multiple trekking routes through five climate zones from rainforest to arctic conditions at the summit.',
                'location': 'Kilimanjaro Region, Tanzania',
                'region': 'Kilimanjaro',
                'category': 'mountain',
                'best_time_to_visit': 'June to October and December to March',
                'entry_fee': '$70 per person per day (park fees) + $50 rescue fee',
                'activities': 'Trekking, Climbing, Photography, Camping, Nature walks',
            },
            {
                'name': 'Tarangire National Park',
                'description': 'Famous for its massive elephant herds (up to 300 in a single group) and iconic baobab trees, Tarangire offers excellent game viewing especially during the dry season when wildlife congregates along the Tarangire River.',
                'location': 'Manyara Region, Tanzania',
                'region': 'Tarangire',
                'category': 'national_park',
                'best_time_to_visit': 'June to October (dry season)',
                'entry_fee': '$60 per person per day',
                'activities': 'Game drives, Bird watching, Photography, Picnic safaris',
            },
            {
                'name': 'Lake Manyara National Park',
                'description': 'Known for its tree-climbing lions and large flamingo populations, Lake Manyara National Park features a diverse landscape of groundwater forests, acacia woodlands, and the alkaline lake itself. The park is home to over 400 bird species.',
                'location': 'Arusha Region, Tanzania',
                'region': 'Manyara',
                'category': 'national_park',
                'best_time_to_visit': 'June to October and December to February',
                'entry_fee': '$60 per person per day',
                'activities': 'Game drives, Canoeing, Bird watching, Walking safaris, Photography',
            },
            {
                'name': 'Selous Game Reserve',
                'description': 'One of the largest faunal reserves in the world covering 50,000 sq km, Selous is a UNESCO World Heritage Site. It offers remote wilderness experiences with boat safaris on the Rufiji River, walking safaris, and excellent wildlife including wild dogs.',
                'location': 'Southern Tanzania',
                'region': 'Selous',
                'category': 'national_park',
                'best_time_to_visit': 'June to October (dry season)',
                'entry_fee': '$50 per person per day',
                'activities': 'Boat safaris, Walking safaris, Game drives, Fishing, Bird watching, Photography',
            },
            {
                'name': 'Ruaha National Park',
                'description': 'Tanzania largest national park (20,300 sq km), Ruaha is known for its dramatic landscapes, massive baobab trees, and large populations of elephants and wild dogs. It offers a remote, uncrowded safari experience.',
                'location': 'Iringa Region, Tanzania',
                'region': 'Ruaha',
                'category': 'national_park',
                'best_time_to_visit': 'June to October (dry season)',
                'entry_fee': '$50 per person per day',
                'activities': 'Game drives, Walking safaris, Bird watching, Photography, Fly camping',
            },
            {
                'name': 'Olduvai Gorge',
                'description': 'One of the most important paleoanthropological sites in the world, Olduvai Gorge is where some of the earliest human remains were discovered by the Leakey family. The site museum displays fascinating fossils and stone tools.',
                'location': 'Ngorongoro Conservation Area, Tanzania',
                'region': 'Ngorongoro',
                'category': 'cultural',
                'best_time_to_visit': 'All year round',
                'entry_fee': '$35 per person',
                'activities': 'Museum visit, Guided site tour, Photography, Educational learning',
            },
            {
                'name': 'Maasai Village Experience',
                'description': 'Visit authentic Maasai bomas (villages) to learn about the traditional semi-nomadic lifestyle of the Maasai people. Experience traditional dancing, beadwork, and learn about their harmonious coexistence with wildlife.',
                'location': 'Various locations near safari parks, Tanzania',
                'region': 'Various',
                'category': 'cultural',
                'best_time_to_visit': 'All year round',
                'entry_fee': '$20-30 per person',
                'activities': 'Cultural tours, Traditional dancing, Beadwork demonstrations, Village walks, Photography',
            },
            {
                'name': 'Arusha National Park',
                'description': 'A small but diverse park featuring Mount Meru (4,566m), the Momela Lakes with flamingos, and lush montane forests. It is home to giraffes, zebras, buffaloes, and offers excellent hiking and canoeing opportunities.',
                'location': 'Arusha, Tanzania',
                'region': 'Arusha',
                'category': 'national_park',
                'best_time_to_visit': 'June to March',
                'entry_fee': '$50 per person per day',
                'activities': 'Game drives, Canoeing, Hiking Mount Meru, Walking safaris, Bird watching, Photography',
            },
            # === ZANZIBAR ATTRACTIONS ===
            {
                'name': 'Stone Town',
                'description': 'The historic heart of Zanzibar City, Stone Town is a UNESCO World Heritage Site. Its maze of narrow alleys features Arab, Indian, and African architecture with carved doors, bustling bazaars, and historic buildings like the House of Wonders and Old Fort.',
                'location': 'Zanzibar City, Zanzibar',
                'region': 'Zanzibar',
                'category': 'cultural',
                'best_time_to_visit': 'All year round',
                'entry_fee': 'Free (guided tours from $20)',
                'activities': 'Walking tours, Shopping, Photography, Historical exploration, Food tours',
            },
            {
                'name': 'Nungwi Beach',
                'description': 'One of the most beautiful beaches in Zanzibar, Nungwi features powdery white sand and crystal-clear turquoise waters. Located at the northern tip, it offers stunning sunsets, excellent swimming conditions, and vibrant beach bars.',
                'location': 'Nungwi, Zanzibar',
                'region': 'Zanzibar',
                'category': 'beach',
                'best_time_to_visit': 'June to October and December to February',
                'entry_fee': 'Free',
                'activities': 'Swimming, Snorkeling, Sunset cruises, Diving, Beach volleyball, Spa treatments',
            },
            {
                'name': 'Mnemba Atoll',
                'description': 'A protected marine reserve off the northeast coast of Zanzibar, Mnemba Atoll is a paradise for snorkelers and divers. The coral reefs are teeming with colorful tropical fish, sea turtles, and dolphins in crystal clear waters.',
                'location': 'Off the coast of Matemwe, Zanzibar',
                'region': 'Zanzibar',
                'category': 'beach',
                'best_time_to_visit': 'All year round (best visibility June to October)',
                'entry_fee': '$50-70 for snorkeling trips',
                'activities': 'Snorkeling, Scuba diving, Dolphin watching, Photography, Swimming',
            },
            {
                'name': 'Jozani Chwaka Bay National Park',
                'description': 'The only national park in Zanzibar, Jozani Forest is home to the rare Red Colobus monkey, found only on this island. The park features groundwater forests, mangroves, and salt marshes with diverse flora and fauna.',
                'location': 'Central Zanzibar',
                'region': 'Zanzibar',
                'category': 'national_park',
                'best_time_to_visit': 'All year round (morning visits recommended)',
                'entry_fee': '$10-15 per person',
                'activities': 'Guided forest walks, Monkey watching, Bird watching, Nature photography, Mangrove boardwalk',
            },
            {
                'name': 'Prison Island (Changuu Island)',
                'description': 'A small island near Stone Town famous for its population of giant Aldabra tortoises, some over 100 years old. Originally built as a prison for rebellious slaves, it now serves as a tourist attraction with beautiful beaches and snorkeling.',
                'location': '3 km northwest of Stone Town, Zanzibar',
                'region': 'Zanzibar',
                'category': 'beach',
                'best_time_to_visit': 'All year round',
                'entry_fee': '$10-15 per person (including boat transfer)',
                'activities': 'Tortoise feeding, Snorkeling, Swimming, Beach relaxation, Photography, History tours',
            },
            {
                'name': 'Kendwa Beach',
                'description': 'Known for its powdery white sand and gentle waters, Kendwa Beach is a favorite for swimming and sunbathing. Unlike many Zanzibar beaches, Kendwa is not affected by tides, making it perfect for swimming at any time of day.',
                'location': 'Kendwa, Zanzibar',
                'region': 'Zanzibar',
                'category': 'beach',
                'best_time_to_visit': 'All year round',
                'entry_fee': 'Free',
                'activities': 'Swimming, Sunbathing, Snorkeling, Kayaking, Stand-up paddleboarding, Beach dining',
            },
            {
                'name': 'Paje Beach',
                'description': 'A stunning beach on the southeast coast of Zanzibar, Paje is famous for its turquoise waters, white sand, and world-class kitesurfing conditions. The area offers a laid-back vibe with beachfront cafes and boutique hotels.',
                'location': 'Paje, Zanzibar',
                'region': 'Zanzibar',
                'category': 'beach',
                'best_time_to_visit': 'June to October and December to February',
                'entry_fee': 'Free',
                'activities': 'Kitesurfing, Windsurfing, Swimming, Snorkeling, Yoga, Beach walks',
            },
            {
                'name': 'Spice Farms of Zanzibar',
                'description': 'Zanzibar is known as the Spice Island, and visiting the spice farms is a must-do experience. Learn about the cultivation of cloves, nutmeg, cinnamon, black pepper, vanilla, and turmeric. Taste fresh tropical fruits and enjoy a traditional Swahili lunch.',
                'location': 'Various locations, Zanzibar',
                'region': 'Zanzibar',
                'category': 'cultural',
                'best_time_to_visit': 'All year round',
                'entry_fee': '$20-25 per person (including guide)',
                'activities': 'Spice tours, Fruit tasting, Cooking demonstrations, Traditional lunch, Photography',
            },
        ]

        for attr_data in attractions:
            att = Attraction.objects.create(**attr_data)
            self.stdout.write(f'  Created attraction: {att.name}')

        reviews_data = [
            {'author_name': 'Sarah Johnson', 'author_title': 'Travel Blogger', 'content': 'The Serengeti safari was absolutely incredible! We saw the Big Five within the first two days. Our guide was knowledgeable and the accommodation was fantastic. Highly recommend this tour!', 'rating': 5, 'tour': Tour.objects.filter(title__icontains='Serengeti').first()},
            {'author_name': 'Michael Chen', 'author_title': 'Adventure Photographer', 'content': 'Kilimanjaro trek was challenging but rewarding beyond words. Standing at Uhuru Peak watching the sunrise was the most incredible experience of my life. The guides and porters were amazing.', 'rating': 5, 'tour': Tour.objects.filter(title__icontains='Kilimanjaro').first()},
            {'author_name': 'Emma Williams', 'author_title': 'Honeymooner', 'content': 'Our honeymoon in Zanzibar was perfect! The beaches were stunning, the resort was luxurious, and the sunset dhow cruise was magical. We will definitely be coming back.', 'rating': 5, 'tour': Tour.objects.filter(title__icontains='Honeymoon').first()},
            {'author_name': 'James Anderson', 'author_title': 'Backpacker', 'content': 'Stone Town is a fascinating place full of history and culture. The spice tour was educational and fun. Zanzibar is truly a unique destination.', 'rating': 4, 'tour': Tour.objects.filter(title__icontains='Stone Town').first()},
            {'author_name': 'Lisa Thompson', 'author_title': 'Wildlife Enthusiast', 'content': 'The Ngorongoro Crater is like nowhere else on earth. The concentration of wildlife is astounding. We saw lions, elephants, rhinos, and thousands of flamingos. Unforgettable!', 'rating': 5, 'tour': Tour.objects.filter(title__icontains='Ngorongoro').first()},
            {'author_name': 'David Martinez', 'author_title': 'Scuba Diver', 'content': 'The snorkeling at Mnemba Atoll was out of this world. Crystal clear water, abundant marine life, and professional guides. A must-do in Zanzibar!', 'rating': 5, 'tour': Tour.objects.filter(title__icontains='Snorkeling').first()},
        ]

        for rev_data in reviews_data:
            if rev_data['tour']:
                Review.objects.create(**rev_data)
                self.stdout.write(f'  Created review by: {rev_data["author_name"]}')

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {Tour.objects.count()} tours, {Attraction.objects.count()} attractions, and {Review.objects.count()} reviews'))
