from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('admin/register/', views.AdminRegisterView.as_view(), name='admin-register'),
    path('user/', views.UserDetailView.as_view(), name='user-detail'),
    path('users/', views.AllUsersView.as_view(), name='user-list'),
    path('users/<int:pk>/', views.UserManageView.as_view(), name='user-manage'),
    path('tours/', views.TourListCreateView.as_view(), name='tour-list'),
    path('tours/<int:pk>/', views.TourDetailView.as_view(), name='tour-detail'),
    path('tours/<int:tour_id>/gallery/', views.TourGalleryListView.as_view(), name='tour-gallery-list'),
    path('tours/<int:tour_id>/gallery/reorder/', views.TourGalleryReorderView.as_view(), name='tour-gallery-reorder'),
    path('tours/<int:tour_id>/gallery/<int:pk>/', views.TourGalleryDetailView.as_view(), name='tour-gallery-image-detail'),
    path('gallery/<int:pk>/', views.TourGalleryDetailView.as_view(), name='tour-gallery-detail'),
    path('attractions/', views.AttractionListCreateView.as_view(), name='attraction-list'),
    path('attractions/<int:pk>/', views.AttractionDetailView.as_view(), name='attraction-detail'),
    path('reviews/', views.ReviewListCreateView.as_view(), name='review-list'),
    path('reviews/<int:pk>/', views.ReviewDetailView.as_view(), name='review-detail'),
    path('reviews/<int:pk>/approve/', views.ReviewApproveView.as_view(), name='review-approve'),
    path('reviews/<int:pk>/user/', views.UserReviewView.as_view(), name='review-user'),
    path('reviews/stats/', views.ReviewStatsView.as_view(), name='review-stats'),
    path('tours/<int:tour_id>/reviews/', views.TourReviewListView.as_view(), name='tour-reviews'),
    path('tours/<int:tour_id>/reviews/create/', views.TourReviewCreateView.as_view(), name='tour-review-create'),
    path('bookings/', views.BookingListCreateView.as_view(), name='booking-list'),
    path('bookings/<int:pk>/', views.BookingDetailView.as_view(), name='booking-detail'),
    path('all-bookings/', views.AllBookingsView.as_view(), name='all-bookings'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('contact/', views.ContactCreateView.as_view(), name='contact'),
    path('messages/', views.ContactMessageListView.as_view(), name='message-list'),
    path('messages/<int:pk>/', views.ContactMessageManageView.as_view(), name='message-manage'),
    path('tips/', views.TravelTipListCreateView.as_view(), name='tip-list'),
    path('tips/<int:pk>/', views.TravelTipDetailView.as_view(), name='tip-detail'),
    path('route/calculate/', views.RouteCalculateView.as_view(), name='route-calculate'),
    path('home-settings/', views.HomeSettingView.as_view(), name='home-settings'),
    path('home-settings/admin/', views.HomeSettingAdminView.as_view(), name='home-settings-admin'),
    path('geocode/', views.GeocodeView.as_view(), name='geocode'),
    path('track-visit/', views.TrackVisitView.as_view(), name='track-visit'),
    path('dashboard/', views.CustomerDashboardView.as_view(), name='customer-dashboard'),
    path('dashboard/stats/', views.DashboardStatsView.as_view(), name='dashboard-stats'),
    path('analytics/', views.AnalyticsView.as_view(), name='analytics'),
    path('send-whatsapp/', views.SendBookingWhatsAppView.as_view(), name='send-whatsapp'),
    path('send-email/', views.SendBookingEmailView.as_view(), name='send-email'),
    # ─── Travel ────────────────────────────────────────────────────────
    path('travel-drivers/', views.TravelDriverListCreateView.as_view(), name='travel-driver-list'),
    path('travel-drivers/<int:pk>/', views.TravelDriverDetailView.as_view(), name='travel-driver-detail'),
    path('travel-vehicles/', views.TravelVehicleListCreateView.as_view(), name='travel-vehicle-list'),
    path('travel-vehicles/<int:pk>/', views.TravelVehicleDetailView.as_view(), name='travel-vehicle-detail'),
    # ─── Hotels ────────────────────────────────────────────────────────
    path('hotels/', views.HotelListCreateView.as_view(), name='hotel-list'),
    path('hotels/<int:pk>/', views.HotelDetailView.as_view(), name='hotel-detail'),
    # ─── Rooms ─────────────────────────────────────────────────────────
    path('rooms/', views.RoomListCreateView.as_view(), name='room-list'),
    path('rooms/<int:pk>/', views.RoomDetailView.as_view(), name='room-detail'),
    # ─── Workspaces ────────────────────────────────────────────────────
    path('workspaces/', views.WorkspaceListCreateView.as_view(), name='workspace-list'),
    path('workspaces/<int:pk>/', views.WorkspaceDetailView.as_view(), name='workspace-detail'),
    path('workspaces/<int:pk>/tours/', views.WorkspaceAddTourView.as_view(), name='workspace-add-tour'),
    path('workspaces/<int:pk>/tours/<int:tour_id>/', views.WorkspaceAddTourView.as_view(), name='workspace-remove-tour'),
    path('workspaces/<int:pk>/hotels/', views.WorkspaceAddHotelView.as_view(), name='workspace-add-hotel'),
    path('workspaces/<int:pk>/rooms/', views.WorkspaceAddRoomView.as_view(), name='workspace-add-room'),
    path('workspaces/<int:pk>/rooms/<int:room_id>/', views.WorkspaceAddRoomView.as_view(), name='workspace-remove-room'),
    path('workspaces/<int:pk>/travel/', views.WorkspaceAddTravelView.as_view(), name='workspace-add-travel'),
    path('workspaces/<int:pk>/travel/<str:type>/', views.WorkspaceAddTravelView.as_view(), name='workspace-remove-travel'),
    path('workspaces/<int:pk>/pricing/', views.WorkspacePricingView.as_view(), name='workspace-pricing'),
    # ─── Workspace Tasks ───────────────────────────────────────────────
    path('workspaces/<int:workspace_pk>/tasks/', views.WorkspaceTaskListCreateView.as_view(), name='workspace-task-list'),
    path('workspaces/<int:workspace_pk>/tasks/<int:pk>/', views.WorkspaceTaskDetailView.as_view(), name='workspace-task-detail'),
]
